language: python
sudo: false
python: 2.7
cache: pip
env:
  - TOXENV="py27_django10"
#  - TOXENV="py27_django11"
install:
  - pip install --upgrade pip setuptools --quiet
  - pip install -r requirements.txt --trusted-host dist.pinaxproject.com --quiet
  - pip install Image --quiet
  - pip install tox --quiet
script:
  - tox -e $TOXENV
notifications:
  slack: makerspacesdl:P1qFqL017sTI0MwENatxRLuM
